name: CI
on:
  push:
    branches: [main, develop, init, "feat/*"]
  pull_request:
    branches: [main, develop, init, "feat/*"]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x", "16.x", "18.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: "Install packages"
        run: npm install
      - name: Lint
        run: npm run lint --if-present
      - name: "Run tests"
        run: npm run test --if-present
      - name: Build
        run: npm run build --if-present
